### ISSUE TITLE
Raw GIF prewiew

### ISSUE THREAD

**Issue by Papagemabodi** [duckythescientist/SmoothLife#9]
when i'm running python it just displays GIF, how do I run the REAL simulation, not gif? HOw do I interact with simulation?

**Comment by duckythescientist** [comment]
When you run Python, it actively computes the simulation. It's not just displaying a gif. If you want to have live interaction with parameters, you'll either have to add it to the code or use a different project (e.g. https://sourceforge.net/projects/smoothlife/).
